version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/db"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"